@startuml
actor User
entity Bot
participant SlashCommandHandler
participant SearchCommandHandler
participant HelpCommandHandler
database Database

User -> Bot: /help
Bot -> SlashCommandHandler: onSlashCommand(event<name:"help">)
SlashCommandHandler -> SlashCommandHandler: Find matching handler for event name "help"
SlashCommandHandler -> HelpCommandHandler: handleCommand()
HelpCommandHandler -> SlashCommandHandler: < a list of commands menu ready to send as a message> 
SlashCommandHandler -> Bot
Bot -> User
...Users read help menu and decide to make a search...

User -> Bot: /search 
Bot -> SlashCommandHandler: onSlashCommand(event<name:"search">)
SlashCommandHandler -> SlashCommandHandler: Find matching handler for even name "search"
SlashCommandHandler -> SearchCommandHandler: handleCommand()
SearchHandler -> Database: <look up 10 jobs ordered by post date by defualt> 
Database -> SearchCommandHandler: <format 10 jobs listings to display in Discord>
SearchCommandHandler -> SlashCommandHandler: <10 jobs ready to send as a message>
SlashCommandHandler -> Bot
Bot -> User



@enduml